name: CI

on: [pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: pnpm install --frozen-lockfile
      - run: pnpm run compile
      - run: pnpm run test
